# Generated by Django 4.2 on 2023-04-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('subgroup_number', models.CharField(max_length=5, verbose_name='Номер подгруппы')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('telegram_id', models.IntegerField(verbose_name='ID телеграм аккаунта')),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='Группа и подгруппа')),
            ],
        ),
    ]
