# Generated by Django 4.2 on 2023-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('telegram_id', models.IntegerField(verbose_name='ID телеграм аккаунта')),
                ('date', models.DateField(verbose_name='Дата посещения')),
            ],
        ),
    ]
