# Generated by Django 4.2 on 2023-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID телеграм аккаунта'),
        ),
    ]
