# Generated by Django 4.2 on 2023-06-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_profile_id_remove_profile_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subgroup_number',
        ),
    ]
