# Generated by Django 4.2 on 2023-04-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('answer_1', models.CharField(max_length=150, verbose_name='Вариант ответа 1')),
                ('answer_2', models.CharField(max_length=150, verbose_name='Вариант ответа 2')),
                ('answer_3', models.CharField(max_length=150, verbose_name='Вариант ответа 3')),
                ('answer_4', models.CharField(max_length=150, verbose_name='Вариант ответа 4')),
                ('correct_answer', models.PositiveSmallIntegerField(verbose_name='Верный ответ')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.category', verbose_name='Категория')),
            ],
        ),
    ]
